---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  azureStorageAccountName: prdffcpayst1001
  endpointEnabled: true
  redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
  redisPort: 6380
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret
      - objectName: prd-redisPassword
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-event-hub
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-redisPassword
          key: REDIS_PASSWORD